title: dhewett.co.uk

author:
  name: Dominic Hewett
  email: dom@dominichewett.co.uk
  
description: >
  Random musings of an Engineer & Entrepreneur

url: "https://dhewett.co.uk" 
  
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

remote_theme: jekyll/minima

minima:   
  skin: auto
  social_links:
    - { platform: github,  user_url: "https://github.com/dhewett" }
    - { platform: twitter, user_url: "https://twitter.com/dhewett" }
    - { platform: mastodon, user_url: "https://mastodon.social/@dhewett" }

header_pages:
  - about.md
  
show_excerpts: true
